(define (problem problemBrandoV5) (:domain domainBrandoV5)
(:objects
sistemiDigitali_1
sistemiDigitali_2
sistemiDigitali_3
analisi_1
analisi_2
analisi_3
componenti_1
componenti_2
componenti_3
componenti_4
componenti_5
componenti_6
componenti_7
sistemiDiMisura_1
sistemiDiMisura_2
sistemiDiMisura_3
sistemiDiMisura_4
sistemiDiMisura_5
sistemiDiMisura_6
sistemiDiMisura_7
sistemiDiMisura_8
sistemiDiMisura_9
- corso

Sisinni
Marcellini
Bau
Serpelloni
- professore

N6
N3
B31
- aula

ITID1
ITID3
- scdla

mon08
mon09
mon10
mon11
mon12
mon13
mon14
mon15
mon16
mon17
mon18

tue08
tue09
tue10
tue11
tue12
tue13
tue14
tue15
tue16
tue17
tue18

wed08
wed09
wed10
wed11
wed12
wed13
wed14
wed15
wed16
wed17
wed18

thu08
thu09
thu10
thu11
thu12
thu13
thu14
thu15
thu16
thu17
thu18

fri08
fri09
fri10
fri11
fri12
fri13
fri14
fri15
fri16
fri17
fri18 - fasciaOraria
)

(:init
(coppiaCorsi sistemiDigitali_1 sistemiDigitali_2)
(coppiaCorsi sistemiDigitali_1 sistemiDigitali_3)
(coppiaCorsi sistemiDigitali_2 sistemiDigitali_3)

(triadeCorsi sistemiDigitali_1 sistemiDigitali_2 sistemiDigitali_3)

(insegna Sisinni sistemiDigitali_1)
(insegna Sisinni sistemiDigitali_2)
(insegna Sisinni sistemiDigitali_3)

(frequenta ITID3 sistemiDigitali_1)
(frequenta ITID3 sistemiDigitali_2)
(frequenta ITID3 sistemiDigitali_3)

(coppiaCorsi analisi_1 analisi_2)
(coppiaCorsi analisi_1 analisi_3)
(coppiaCorsi analisi_2 analisi_3)

(triadeCorsi analisi_1 analisi_2 analisi_3)

(insegna Marcellini analisi_1)
(insegna Marcellini analisi_2)
(insegna Marcellini analisi_3)

(frequenta ITID1 analisi_1)
(frequenta ITID1 analisi_2)
(frequenta ITID1 analisi_3)

(coppiaCorsi componenti_1 componenti_2)
(coppiaCorsi componenti_1 componenti_3)
(coppiaCorsi componenti_1 componenti_4)
(coppiaCorsi componenti_1 componenti_5)
(coppiaCorsi componenti_1 componenti_6)
(coppiaCorsi componenti_1 componenti_7)
(coppiaCorsi componenti_2 componenti_3)
(coppiaCorsi componenti_2 componenti_4)
(coppiaCorsi componenti_2 componenti_5)
(coppiaCorsi componenti_2 componenti_6)
(coppiaCorsi componenti_2 componenti_7)
(coppiaCorsi componenti_3 componenti_4)
(coppiaCorsi componenti_3 componenti_5)
(coppiaCorsi componenti_3 componenti_6)
(coppiaCorsi componenti_3 componenti_7)
(coppiaCorsi componenti_4 componenti_5)
(coppiaCorsi componenti_4 componenti_6)
(coppiaCorsi componenti_4 componenti_7)
(coppiaCorsi componenti_5 componenti_6)
(coppiaCorsi componenti_5 componenti_7)
(coppiaCorsi componenti_6 componenti_7)

(triadeCorsi componenti_1 componenti_2 componenti_3)
(triadeCorsi componenti_1 componenti_2 componenti_4)
(triadeCorsi componenti_1 componenti_2 componenti_5)
(triadeCorsi componenti_1 componenti_2 componenti_6)
(triadeCorsi componenti_1 componenti_2 componenti_7)
(triadeCorsi componenti_1 componenti_3 componenti_4)
(triadeCorsi componenti_1 componenti_3 componenti_5)
(triadeCorsi componenti_1 componenti_3 componenti_6)
(triadeCorsi componenti_1 componenti_3 componenti_7)
(triadeCorsi componenti_1 componenti_4 componenti_5)
(triadeCorsi componenti_1 componenti_4 componenti_6)
(triadeCorsi componenti_1 componenti_4 componenti_7)
(triadeCorsi componenti_1 componenti_5 componenti_6)
(triadeCorsi componenti_1 componenti_5 componenti_7)
(triadeCorsi componenti_1 componenti_6 componenti_7)
(triadeCorsi componenti_2 componenti_3 componenti_4)
(triadeCorsi componenti_2 componenti_3 componenti_5)
(triadeCorsi componenti_2 componenti_3 componenti_6)
(triadeCorsi componenti_2 componenti_3 componenti_7)
(triadeCorsi componenti_2 componenti_4 componenti_5)
(triadeCorsi componenti_2 componenti_4 componenti_6)
(triadeCorsi componenti_2 componenti_4 componenti_7)
(triadeCorsi componenti_2 componenti_5 componenti_6)
(triadeCorsi componenti_2 componenti_5 componenti_7)
(triadeCorsi componenti_2 componenti_6 componenti_7)
(triadeCorsi componenti_3 componenti_4 componenti_5)
(triadeCorsi componenti_3 componenti_4 componenti_6)
(triadeCorsi componenti_3 componenti_4 componenti_7)
(triadeCorsi componenti_3 componenti_5 componenti_6)
(triadeCorsi componenti_3 componenti_5 componenti_7)
(triadeCorsi componenti_3 componenti_6 componenti_7)
(triadeCorsi componenti_4 componenti_5 componenti_6)
(triadeCorsi componenti_4 componenti_5 componenti_7)
(triadeCorsi componenti_4 componenti_6 componenti_7)
(triadeCorsi componenti_5 componenti_6 componenti_7)

(quartettoCorsi componenti_1 componenti_2 componenti_3 componenti_4)
(quartettoCorsi componenti_1 componenti_2 componenti_3 componenti_5)
(quartettoCorsi componenti_1 componenti_2 componenti_3 componenti_6)
(quartettoCorsi componenti_1 componenti_2 componenti_3 componenti_7)
(quartettoCorsi componenti_1 componenti_2 componenti_4 componenti_5)
(quartettoCorsi componenti_1 componenti_2 componenti_4 componenti_6)
(quartettoCorsi componenti_1 componenti_2 componenti_4 componenti_7)
(quartettoCorsi componenti_1 componenti_2 componenti_5 componenti_6)
(quartettoCorsi componenti_1 componenti_2 componenti_5 componenti_7)
(quartettoCorsi componenti_1 componenti_2 componenti_6 componenti_7)
(quartettoCorsi componenti_1 componenti_3 componenti_4 componenti_5)
(quartettoCorsi componenti_1 componenti_3 componenti_4 componenti_6)
(quartettoCorsi componenti_1 componenti_3 componenti_4 componenti_7)
(quartettoCorsi componenti_1 componenti_3 componenti_5 componenti_6)
(quartettoCorsi componenti_1 componenti_3 componenti_5 componenti_7)
(quartettoCorsi componenti_1 componenti_3 componenti_6 componenti_7)
(quartettoCorsi componenti_1 componenti_4 componenti_5 componenti_6)
(quartettoCorsi componenti_1 componenti_4 componenti_5 componenti_7)
(quartettoCorsi componenti_1 componenti_4 componenti_6 componenti_7)
(quartettoCorsi componenti_1 componenti_5 componenti_6 componenti_7)
(quartettoCorsi componenti_2 componenti_3 componenti_4 componenti_5)
(quartettoCorsi componenti_2 componenti_3 componenti_4 componenti_6)
(quartettoCorsi componenti_2 componenti_3 componenti_4 componenti_7)
(quartettoCorsi componenti_2 componenti_3 componenti_5 componenti_6)
(quartettoCorsi componenti_2 componenti_3 componenti_5 componenti_7)
(quartettoCorsi componenti_2 componenti_3 componenti_6 componenti_7)
(quartettoCorsi componenti_2 componenti_4 componenti_5 componenti_6)
(quartettoCorsi componenti_2 componenti_4 componenti_5 componenti_7)
(quartettoCorsi componenti_2 componenti_4 componenti_6 componenti_7)
(quartettoCorsi componenti_2 componenti_5 componenti_6 componenti_7)
(quartettoCorsi componenti_3 componenti_4 componenti_5 componenti_6)
(quartettoCorsi componenti_3 componenti_4 componenti_5 componenti_7)
(quartettoCorsi componenti_3 componenti_4 componenti_6 componenti_7)
(quartettoCorsi componenti_3 componenti_5 componenti_6 componenti_7)
(quartettoCorsi componenti_4 componenti_5 componenti_6 componenti_7)

(insegna Bau componenti_1)
(insegna Bau componenti_2)
(insegna Bau componenti_3)
(insegna Bau componenti_4)
(insegna Bau componenti_5)
(insegna Bau componenti_6)
(insegna Bau componenti_7)

(frequenta ITID3 componenti_1)
(frequenta ITID3 componenti_2)
(frequenta ITID3 componenti_3)
(frequenta ITID3 componenti_4)
(frequenta ITID3 componenti_5)
(frequenta ITID3 componenti_6)
(frequenta ITID3 componenti_7)

(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_2)
(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_3)
(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_4)
(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_5)
(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_6)
(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_7)
(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_8)
(coppiaCorsi sistemiDiMisura_1 sistemiDiMisura_9)
(coppiaCorsi sistemiDiMisura_2 sistemiDiMisura_3)
(coppiaCorsi sistemiDiMisura_2 sistemiDiMisura_4)
(coppiaCorsi sistemiDiMisura_2 sistemiDiMisura_5)
(coppiaCorsi sistemiDiMisura_2 sistemiDiMisura_6)
(coppiaCorsi sistemiDiMisura_2 sistemiDiMisura_7)
(coppiaCorsi sistemiDiMisura_2 sistemiDiMisura_8)
(coppiaCorsi sistemiDiMisura_2 sistemiDiMisura_9)
(coppiaCorsi sistemiDiMisura_3 sistemiDiMisura_4)
(coppiaCorsi sistemiDiMisura_3 sistemiDiMisura_5)
(coppiaCorsi sistemiDiMisura_3 sistemiDiMisura_6)
(coppiaCorsi sistemiDiMisura_3 sistemiDiMisura_7)
(coppiaCorsi sistemiDiMisura_3 sistemiDiMisura_8)
(coppiaCorsi sistemiDiMisura_3 sistemiDiMisura_9)
(coppiaCorsi sistemiDiMisura_4 sistemiDiMisura_5)
(coppiaCorsi sistemiDiMisura_4 sistemiDiMisura_6)
(coppiaCorsi sistemiDiMisura_4 sistemiDiMisura_7)
(coppiaCorsi sistemiDiMisura_4 sistemiDiMisura_8)
(coppiaCorsi sistemiDiMisura_4 sistemiDiMisura_9)
(coppiaCorsi sistemiDiMisura_5 sistemiDiMisura_6)
(coppiaCorsi sistemiDiMisura_5 sistemiDiMisura_7)
(coppiaCorsi sistemiDiMisura_5 sistemiDiMisura_8)
(coppiaCorsi sistemiDiMisura_5 sistemiDiMisura_9)
(coppiaCorsi sistemiDiMisura_6 sistemiDiMisura_7)
(coppiaCorsi sistemiDiMisura_6 sistemiDiMisura_8)
(coppiaCorsi sistemiDiMisura_6 sistemiDiMisura_9)
(coppiaCorsi sistemiDiMisura_7 sistemiDiMisura_8)
(coppiaCorsi sistemiDiMisura_7 sistemiDiMisura_9)
(coppiaCorsi sistemiDiMisura_8 sistemiDiMisura_9)

(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_3)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_4)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_5)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_4)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_5)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_5)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_6 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_6 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_6 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_7 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_7 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_1 sistemiDiMisura_8 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_4)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_5)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_5)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_7 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_7 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_2 sistemiDiMisura_8 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_5)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_7 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_7 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_3 sistemiDiMisura_8 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_6)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_4 sistemiDiMisura_8 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_7)
(triadeCorsi sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_5 sistemiDiMisura_8 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_8)
(triadeCorsi sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_6 sistemiDiMisura_8 sistemiDiMisura_9)
(triadeCorsi sistemiDiMisura_7 sistemiDiMisura_8 sistemiDiMisura_9)

(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_4)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_5)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_5)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_2 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_5)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_3 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_4 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_5 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_6 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_1 sistemiDiMisura_7 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_5)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_3 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_4 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_5 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_6 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_2 sistemiDiMisura_7 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_6)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_4 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_5 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_6 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_3 sistemiDiMisura_7 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_7)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_5 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_6 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_4 sistemiDiMisura_7 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_8)
(quartettoCorsi sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_5 sistemiDiMisura_6 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_5 sistemiDiMisura_7 sistemiDiMisura_8 sistemiDiMisura_9)
(quartettoCorsi sistemiDiMisura_6 sistemiDiMisura_7 sistemiDiMisura_8 sistemiDiMisura_9)

(insegna Serpelloni sistemiDiMisura_1)
(insegna Serpelloni sistemiDiMisura_2)
(insegna Serpelloni sistemiDiMisura_3)
(insegna Serpelloni sistemiDiMisura_4)
(insegna Serpelloni sistemiDiMisura_5)
(insegna Serpelloni sistemiDiMisura_6)
(insegna Serpelloni sistemiDiMisura_7)
(insegna Serpelloni sistemiDiMisura_8)
(insegna Serpelloni sistemiDiMisura_9)

(frequenta ITID3 sistemiDiMisura_1)
(frequenta ITID3 sistemiDiMisura_2)
(frequenta ITID3 sistemiDiMisura_3)
(frequenta ITID3 sistemiDiMisura_4)
(frequenta ITID3 sistemiDiMisura_5)
(frequenta ITID3 sistemiDiMisura_6)
(frequenta ITID3 sistemiDiMisura_7)
(frequenta ITID3 sistemiDiMisura_8)
(frequenta ITID3 sistemiDiMisura_9)

(profDisponibile Sisinni mon08)
(profDisponibile Sisinni mon09)
(profDisponibile Sisinni mon10)
(profDisponibile Sisinni mon11)
(profDisponibile Sisinni mon12)
(profDisponibile Sisinni mon13)
(profDisponibile Sisinni mon14)
(profDisponibile Sisinni mon15)
(profDisponibile Sisinni mon16)
(profDisponibile Sisinni mon17)
(profDisponibile Sisinni mon18)
(profDisponibile Sisinni tue08)
(profDisponibile Sisinni tue09)
(profDisponibile Sisinni tue10)
(profDisponibile Sisinni tue11)
(profDisponibile Sisinni tue12)
(profDisponibile Sisinni tue13)
(profDisponibile Sisinni tue14)
(profDisponibile Sisinni tue15)
(profDisponibile Sisinni tue16)
(profDisponibile Sisinni tue17)
(profDisponibile Sisinni tue18)
(profDisponibile Sisinni wed08)
(profDisponibile Sisinni wed09)
(profDisponibile Sisinni wed10)
(profDisponibile Sisinni wed11)
(profDisponibile Sisinni wed12)
(profDisponibile Sisinni wed13)
(profDisponibile Sisinni wed14)
(profDisponibile Sisinni wed15)
(profDisponibile Sisinni wed16)
(profDisponibile Sisinni wed17)
(profDisponibile Sisinni wed18)
(profDisponibile Sisinni thu08)
(profDisponibile Sisinni thu09)
(profDisponibile Sisinni thu10)
(profDisponibile Sisinni thu11)
(profDisponibile Sisinni thu12)
(profDisponibile Sisinni thu13)
(profDisponibile Sisinni thu14)
(profDisponibile Sisinni thu15)
(profDisponibile Sisinni thu16)
(profDisponibile Sisinni thu17)
(profDisponibile Sisinni thu18)
(profDisponibile Sisinni fri08)
(profDisponibile Sisinni fri09)
(profDisponibile Sisinni fri10)
(profDisponibile Sisinni fri11)
(profDisponibile Sisinni fri12)
(profDisponibile Sisinni fri13)
(profDisponibile Sisinni fri14)
(profDisponibile Sisinni fri15)
(profDisponibile Sisinni fri16)
(profDisponibile Sisinni fri17)
(profDisponibile Sisinni fri18)
(profDisponibile Marcellini mon08)
(profDisponibile Marcellini mon09)
(profDisponibile Marcellini mon10)
(profDisponibile Marcellini mon11)
(profDisponibile Marcellini mon12)
(profDisponibile Marcellini mon13)
(profDisponibile Marcellini mon14)
(profDisponibile Marcellini mon15)
(profDisponibile Marcellini mon16)
(profDisponibile Marcellini mon17)
(profDisponibile Marcellini mon18)
(profDisponibile Marcellini tue08)
(profDisponibile Marcellini tue09)
(profDisponibile Marcellini tue10)
(profDisponibile Marcellini tue11)
(profDisponibile Marcellini tue12)
(profDisponibile Marcellini tue13)
(profDisponibile Marcellini tue14)
(profDisponibile Marcellini tue15)
(profDisponibile Marcellini tue16)
(profDisponibile Marcellini tue17)
(profDisponibile Marcellini tue18)
(profDisponibile Marcellini wed08)
(profDisponibile Marcellini wed09)
(profDisponibile Marcellini wed10)
(profDisponibile Marcellini wed11)
(profDisponibile Marcellini wed12)
(profDisponibile Marcellini wed13)
(profDisponibile Marcellini wed14)
(profDisponibile Marcellini wed15)
(profDisponibile Marcellini wed16)
(profDisponibile Marcellini wed17)
(profDisponibile Marcellini wed18)
(profDisponibile Marcellini thu08)
(profDisponibile Marcellini thu09)
(profDisponibile Marcellini thu10)
(profDisponibile Marcellini thu11)
(profDisponibile Marcellini thu12)
(profDisponibile Marcellini thu13)
(profDisponibile Marcellini thu14)
(profDisponibile Marcellini thu15)
(profDisponibile Marcellini thu16)
(profDisponibile Marcellini thu17)
(profDisponibile Marcellini thu18)
(profDisponibile Marcellini fri08)
(profDisponibile Marcellini fri09)
(profDisponibile Marcellini fri10)
(profDisponibile Marcellini fri11)
(profDisponibile Marcellini fri12)
(profDisponibile Marcellini fri13)
(profDisponibile Marcellini fri14)
(profDisponibile Marcellini fri15)
(profDisponibile Marcellini fri16)
(profDisponibile Marcellini fri17)
(profDisponibile Marcellini fri18)
(profDisponibile Bau mon08)
(profDisponibile Bau mon09)
(profDisponibile Bau mon10)
(profDisponibile Bau mon11)
(profDisponibile Bau mon12)
(profDisponibile Bau mon13)
(profDisponibile Bau mon14)
(profDisponibile Bau mon15)
(profDisponibile Bau mon16)
(profDisponibile Bau mon17)
(profDisponibile Bau mon18)
(profDisponibile Bau tue08)
(profDisponibile Bau tue09)
(profDisponibile Bau tue10)
(profDisponibile Bau tue11)
(profDisponibile Bau tue12)
(profDisponibile Bau tue13)
(profDisponibile Bau tue14)
(profDisponibile Bau tue15)
(profDisponibile Bau tue16)
(profDisponibile Bau tue17)
(profDisponibile Bau tue18)
(profDisponibile Bau wed08)
(profDisponibile Bau wed09)
(profDisponibile Bau wed10)
(profDisponibile Bau wed11)
(profDisponibile Bau wed12)
(profDisponibile Bau wed13)
(profDisponibile Bau wed14)
(profDisponibile Bau wed15)
(profDisponibile Bau wed16)
(profDisponibile Bau wed17)
(profDisponibile Bau wed18)
(profDisponibile Bau thu08)
(profDisponibile Bau thu09)
(profDisponibile Bau thu10)
(profDisponibile Bau thu11)
(profDisponibile Bau thu12)
(profDisponibile Bau thu13)
(profDisponibile Bau thu14)
(profDisponibile Bau thu15)
(profDisponibile Bau thu16)
(profDisponibile Bau thu17)
(profDisponibile Bau thu18)
(profDisponibile Bau fri08)
(profDisponibile Bau fri09)
(profDisponibile Bau fri10)
(profDisponibile Bau fri11)
(profDisponibile Bau fri12)
(profDisponibile Bau fri13)
(profDisponibile Bau fri14)
(profDisponibile Bau fri15)
(profDisponibile Bau fri16)
(profDisponibile Bau fri17)
(profDisponibile Bau fri18)
(profDisponibile Serpelloni tue08)
(profDisponibile Serpelloni tue09)
(profDisponibile Serpelloni tue10)
(profDisponibile Serpelloni tue11)
(profDisponibile Serpelloni tue12)
(profDisponibile Serpelloni tue13)
(profDisponibile Serpelloni tue14)
(profDisponibile Serpelloni tue15)
(profDisponibile Serpelloni tue16)
(profDisponibile Serpelloni tue17)
(profDisponibile Serpelloni tue18)
(profDisponibile Serpelloni wed08)
(profDisponibile Serpelloni wed09)
(profDisponibile Serpelloni wed10)
(profDisponibile Serpelloni wed11)
(profDisponibile Serpelloni wed12)
(profDisponibile Serpelloni wed13)
(profDisponibile Serpelloni wed14)
(profDisponibile Serpelloni wed15)
(profDisponibile Serpelloni wed16)
(profDisponibile Serpelloni wed17)
(profDisponibile Serpelloni wed18)
(profDisponibile Serpelloni thu08)
(profDisponibile Serpelloni thu09)
(profDisponibile Serpelloni thu10)
(profDisponibile Serpelloni thu11)
(profDisponibile Serpelloni thu12)
(profDisponibile Serpelloni thu13)
(profDisponibile Serpelloni thu14)
(profDisponibile Serpelloni thu15)
(profDisponibile Serpelloni thu16)
(profDisponibile Serpelloni thu17)
(profDisponibile Serpelloni thu18)
(profDisponibile Serpelloni fri08)
(profDisponibile Serpelloni fri09)
(profDisponibile Serpelloni fri10)
(profDisponibile Serpelloni fri11)
(profDisponibile Serpelloni fri12)
(profDisponibile Serpelloni fri13)
(profDisponibile Serpelloni fri14)
(profDisponibile Serpelloni fri15)
(profDisponibile Serpelloni fri16)
(profDisponibile Serpelloni fri17)
(profDisponibile Serpelloni fri18)

(aulaDisponibile N6 tue08)
(aulaDisponibile N6 tue09)
(aulaDisponibile N6 tue10)
(aulaDisponibile N6 tue11)
(aulaDisponibile N6 tue12)
(aulaDisponibile N6 tue13)
(aulaDisponibile N6 tue14)
(aulaDisponibile N6 tue15)
(aulaDisponibile N6 tue16)
(aulaDisponibile N6 tue17)
(aulaDisponibile N6 tue18)
(aulaDisponibile N6 wed08)
(aulaDisponibile N6 wed09)
(aulaDisponibile N6 wed10)
(aulaDisponibile N6 wed11)
(aulaDisponibile N6 wed12)
(aulaDisponibile N6 wed13)
(aulaDisponibile N6 wed14)
(aulaDisponibile N6 wed15)
(aulaDisponibile N6 wed16)
(aulaDisponibile N6 wed17)
(aulaDisponibile N6 wed18)
(aulaDisponibile N6 thu08)
(aulaDisponibile N6 thu09)
(aulaDisponibile N6 thu10)
(aulaDisponibile N6 thu11)
(aulaDisponibile N6 thu12)
(aulaDisponibile N6 thu13)
(aulaDisponibile N6 thu14)
(aulaDisponibile N6 thu15)
(aulaDisponibile N6 thu16)
(aulaDisponibile N6 thu17)
(aulaDisponibile N6 thu18)
(aulaDisponibile N6 fri08)
(aulaDisponibile N6 fri09)
(aulaDisponibile N6 fri10)
(aulaDisponibile N6 fri11)
(aulaDisponibile N6 fri12)
(aulaDisponibile N6 fri13)
(aulaDisponibile N6 fri14)
(aulaDisponibile N6 fri15)
(aulaDisponibile N6 fri16)
(aulaDisponibile N6 fri17)
(aulaDisponibile N6 fri18)
(aulaDisponibile N3 mon08)
(aulaDisponibile N3 mon09)
(aulaDisponibile N3 mon10)
(aulaDisponibile N3 mon11)
(aulaDisponibile N3 mon12)
(aulaDisponibile N3 mon13)
(aulaDisponibile N3 mon14)
(aulaDisponibile N3 mon15)
(aulaDisponibile N3 mon16)
(aulaDisponibile N3 mon17)
(aulaDisponibile N3 mon18)
(aulaDisponibile N3 tue08)
(aulaDisponibile N3 tue09)
(aulaDisponibile N3 tue10)
(aulaDisponibile N3 tue11)
(aulaDisponibile N3 tue12)
(aulaDisponibile N3 tue13)
(aulaDisponibile N3 tue14)
(aulaDisponibile N3 tue15)
(aulaDisponibile N3 tue16)
(aulaDisponibile N3 tue17)
(aulaDisponibile N3 tue18)
(aulaDisponibile N3 wed08)
(aulaDisponibile N3 wed09)
(aulaDisponibile N3 wed10)
(aulaDisponibile N3 wed11)
(aulaDisponibile N3 wed12)
(aulaDisponibile N3 wed13)
(aulaDisponibile N3 wed14)
(aulaDisponibile N3 wed15)
(aulaDisponibile N3 wed16)
(aulaDisponibile N3 wed17)
(aulaDisponibile N3 wed18)
(aulaDisponibile N3 thu08)
(aulaDisponibile N3 thu09)
(aulaDisponibile N3 thu10)
(aulaDisponibile N3 thu11)
(aulaDisponibile N3 thu12)
(aulaDisponibile N3 thu13)
(aulaDisponibile N3 thu14)
(aulaDisponibile N3 thu15)
(aulaDisponibile N3 thu16)
(aulaDisponibile N3 thu17)
(aulaDisponibile N3 thu18)
(aulaDisponibile N3 fri08)
(aulaDisponibile N3 fri09)
(aulaDisponibile N3 fri10)
(aulaDisponibile N3 fri11)
(aulaDisponibile N3 fri12)
(aulaDisponibile N3 fri13)
(aulaDisponibile N3 fri14)
(aulaDisponibile N3 fri15)
(aulaDisponibile N3 fri16)
(aulaDisponibile N3 fri17)
(aulaDisponibile N3 fri18)
(aulaDisponibile B31 mon08)
(aulaDisponibile B31 mon09)
(aulaDisponibile B31 mon10)
(aulaDisponibile B31 mon11)
(aulaDisponibile B31 mon12)
(aulaDisponibile B31 mon13)
(aulaDisponibile B31 mon14)
(aulaDisponibile B31 mon15)
(aulaDisponibile B31 mon16)
(aulaDisponibile B31 mon17)
(aulaDisponibile B31 mon18)
(aulaDisponibile B31 tue08)
(aulaDisponibile B31 tue09)
(aulaDisponibile B31 tue10)
(aulaDisponibile B31 tue11)
(aulaDisponibile B31 tue12)
(aulaDisponibile B31 tue13)
(aulaDisponibile B31 tue14)
(aulaDisponibile B31 tue15)
(aulaDisponibile B31 tue16)
(aulaDisponibile B31 tue17)
(aulaDisponibile B31 tue18)
(aulaDisponibile B31 wed08)
(aulaDisponibile B31 wed09)
(aulaDisponibile B31 wed10)
(aulaDisponibile B31 wed11)
(aulaDisponibile B31 wed12)
(aulaDisponibile B31 wed13)
(aulaDisponibile B31 wed14)
(aulaDisponibile B31 wed15)
(aulaDisponibile B31 wed16)
(aulaDisponibile B31 wed17)
(aulaDisponibile B31 wed18)
(aulaDisponibile B31 thu08)
(aulaDisponibile B31 thu09)
(aulaDisponibile B31 thu10)
(aulaDisponibile B31 thu11)
(aulaDisponibile B31 thu12)
(aulaDisponibile B31 thu13)
(aulaDisponibile B31 thu14)
(aulaDisponibile B31 thu15)
(aulaDisponibile B31 thu16)
(aulaDisponibile B31 thu17)
(aulaDisponibile B31 thu18)
(aulaDisponibile B31 fri08)
(aulaDisponibile B31 fri09)
(aulaDisponibile B31 fri10)
(aulaDisponibile B31 fri11)
(aulaDisponibile B31 fri12)
(aulaDisponibile B31 fri13)
(aulaDisponibile B31 fri14)
(aulaDisponibile B31 fri15)
(aulaDisponibile B31 fri16)
(aulaDisponibile B31 fri17)
(aulaDisponibile B31 fri18)

(scdlaDisponibile ITID1 mon08)
(scdlaDisponibile ITID1 mon09)
(scdlaDisponibile ITID1 mon10)
(scdlaDisponibile ITID1 mon11)
(scdlaDisponibile ITID1 mon12)
(scdlaDisponibile ITID1 mon13)
(scdlaDisponibile ITID1 mon14)
(scdlaDisponibile ITID1 mon15)
(scdlaDisponibile ITID1 mon16)
(scdlaDisponibile ITID1 mon17)
(scdlaDisponibile ITID1 mon18)
(scdlaDisponibile ITID1 wed08)
(scdlaDisponibile ITID1 wed09)
(scdlaDisponibile ITID1 wed10)
(scdlaDisponibile ITID1 wed11)
(scdlaDisponibile ITID1 wed12)
(scdlaDisponibile ITID1 wed13)
(scdlaDisponibile ITID1 wed14)
(scdlaDisponibile ITID1 wed15)
(scdlaDisponibile ITID1 wed16)
(scdlaDisponibile ITID1 wed17)
(scdlaDisponibile ITID1 wed18)
(scdlaDisponibile ITID1 thu08)
(scdlaDisponibile ITID1 thu09)
(scdlaDisponibile ITID1 thu10)
(scdlaDisponibile ITID1 thu11)
(scdlaDisponibile ITID1 thu12)
(scdlaDisponibile ITID1 thu13)
(scdlaDisponibile ITID1 thu14)
(scdlaDisponibile ITID1 thu15)
(scdlaDisponibile ITID1 thu16)
(scdlaDisponibile ITID1 thu17)
(scdlaDisponibile ITID1 thu18)
(scdlaDisponibile ITID1 fri08)
(scdlaDisponibile ITID1 fri09)
(scdlaDisponibile ITID1 fri10)
(scdlaDisponibile ITID1 fri11)
(scdlaDisponibile ITID1 fri12)
(scdlaDisponibile ITID1 fri13)
(scdlaDisponibile ITID1 fri14)
(scdlaDisponibile ITID1 fri15)
(scdlaDisponibile ITID1 fri16)
(scdlaDisponibile ITID1 fri17)
(scdlaDisponibile ITID1 fri18)
(scdlaDisponibile ITID3 mon08)
(scdlaDisponibile ITID3 mon09)
(scdlaDisponibile ITID3 mon10)
(scdlaDisponibile ITID3 mon11)
(scdlaDisponibile ITID3 mon12)
(scdlaDisponibile ITID3 mon13)
(scdlaDisponibile ITID3 mon14)
(scdlaDisponibile ITID3 mon15)
(scdlaDisponibile ITID3 mon16)
(scdlaDisponibile ITID3 mon17)
(scdlaDisponibile ITID3 mon18)
(scdlaDisponibile ITID3 tue08)
(scdlaDisponibile ITID3 tue09)
(scdlaDisponibile ITID3 tue10)
(scdlaDisponibile ITID3 tue11)
(scdlaDisponibile ITID3 tue12)
(scdlaDisponibile ITID3 tue13)
(scdlaDisponibile ITID3 tue14)
(scdlaDisponibile ITID3 tue15)
(scdlaDisponibile ITID3 tue16)
(scdlaDisponibile ITID3 tue17)
(scdlaDisponibile ITID3 tue18)
(scdlaDisponibile ITID3 wed08)
(scdlaDisponibile ITID3 wed09)
(scdlaDisponibile ITID3 wed10)
(scdlaDisponibile ITID3 wed11)
(scdlaDisponibile ITID3 wed12)
(scdlaDisponibile ITID3 wed13)
(scdlaDisponibile ITID3 wed14)
(scdlaDisponibile ITID3 wed15)
(scdlaDisponibile ITID3 wed16)
(scdlaDisponibile ITID3 wed17)
(scdlaDisponibile ITID3 wed18)
(scdlaDisponibile ITID3 thu08)
(scdlaDisponibile ITID3 thu09)
(scdlaDisponibile ITID3 thu10)
(scdlaDisponibile ITID3 thu11)
(scdlaDisponibile ITID3 thu12)
(scdlaDisponibile ITID3 thu13)
(scdlaDisponibile ITID3 thu14)
(scdlaDisponibile ITID3 thu15)
(scdlaDisponibile ITID3 thu16)
(scdlaDisponibile ITID3 thu17)
(scdlaDisponibile ITID3 thu18)
(scdlaDisponibile ITID3 fri08)
(scdlaDisponibile ITID3 fri09)
(scdlaDisponibile ITID3 fri10)
(scdlaDisponibile ITID3 fri11)
(scdlaDisponibile ITID3 fri12)
(scdlaDisponibile ITID3 fri13)
(scdlaDisponibile ITID3 fri14)
(scdlaDisponibile ITID3 fri15)
(scdlaDisponibile ITID3 fri16)
(scdlaDisponibile ITID3 fri17)
(scdlaDisponibile ITID3 fri18)

(coppiaFasceOrarie mon08 mon09)
(coppiaFasceOrarie mon09 mon10)
(coppiaFasceOrarie mon10 mon11)
(coppiaFasceOrarie mon11 mon12)
(coppiaFasceOrarie mon12 mon13)
(coppiaFasceOrarie mon13 mon14)
(coppiaFasceOrarie mon14 mon15)
(coppiaFasceOrarie mon15 mon16)
(coppiaFasceOrarie mon16 mon17)
(coppiaFasceOrarie mon17 mon18)

(triadeFasceOrarie mon08 mon09 mon10)
(triadeFasceOrarie mon09 mon10 mon11)
(triadeFasceOrarie mon10 mon11 mon12)
(triadeFasceOrarie mon11 mon12 mon13)
(triadeFasceOrarie mon12 mon13 mon14)
(triadeFasceOrarie mon13 mon14 mon15)
(triadeFasceOrarie mon14 mon15 mon16)
(triadeFasceOrarie mon15 mon16 mon17)
(triadeFasceOrarie mon16 mon17 mon18)

(quartettoFasceOrarie mon08 mon09 mon10 mon11)
(quartettoFasceOrarie mon09 mon10 mon11 mon12)
(quartettoFasceOrarie mon10 mon11 mon12 mon13)
(quartettoFasceOrarie mon11 mon12 mon13 mon14)
(quartettoFasceOrarie mon12 mon13 mon14 mon15)
(quartettoFasceOrarie mon13 mon14 mon15 mon16)
(quartettoFasceOrarie mon14 mon15 mon16 mon17)
(quartettoFasceOrarie mon15 mon16 mon17 mon18)

(coppiaFasceOrarie tue08 tue09)
(coppiaFasceOrarie tue09 tue10)
(coppiaFasceOrarie tue10 tue11)
(coppiaFasceOrarie tue11 tue12)
(coppiaFasceOrarie tue12 tue13)
(coppiaFasceOrarie tue13 tue14)
(coppiaFasceOrarie tue14 tue15)
(coppiaFasceOrarie tue15 tue16)
(coppiaFasceOrarie tue16 tue17)
(coppiaFasceOrarie tue17 tue18)

(triadeFasceOrarie tue08 tue09 tue10)
(triadeFasceOrarie tue09 tue10 tue11)
(triadeFasceOrarie tue10 tue11 tue12)
(triadeFasceOrarie tue11 tue12 tue13)
(triadeFasceOrarie tue12 tue13 tue14)
(triadeFasceOrarie tue13 tue14 tue15)
(triadeFasceOrarie tue14 tue15 tue16)
(triadeFasceOrarie tue15 tue16 tue17)
(triadeFasceOrarie tue16 tue17 tue18)

(quartettoFasceOrarie tue08 tue09 tue10 tue11)
(quartettoFasceOrarie tue09 tue10 tue11 tue12)
(quartettoFasceOrarie tue10 tue11 tue12 tue13)
(quartettoFasceOrarie tue11 tue12 tue13 tue14)
(quartettoFasceOrarie tue12 tue13 tue14 tue15)
(quartettoFasceOrarie tue13 tue14 tue15 tue16)
(quartettoFasceOrarie tue14 tue15 tue16 tue17)
(quartettoFasceOrarie tue15 tue16 tue17 tue18)

(coppiaFasceOrarie wed08 wed09)
(coppiaFasceOrarie wed09 wed10)
(coppiaFasceOrarie wed10 wed11)
(coppiaFasceOrarie wed11 wed12)
(coppiaFasceOrarie wed12 wed13)
(coppiaFasceOrarie wed13 wed14)
(coppiaFasceOrarie wed14 wed15)
(coppiaFasceOrarie wed15 wed16)
(coppiaFasceOrarie wed16 wed17)
(coppiaFasceOrarie wed17 wed18)

(triadeFasceOrarie wed08 wed09 wed10)
(triadeFasceOrarie wed09 wed10 wed11)
(triadeFasceOrarie wed10 wed11 wed12)
(triadeFasceOrarie wed11 wed12 wed13)
(triadeFasceOrarie wed12 wed13 wed14)
(triadeFasceOrarie wed13 wed14 wed15)
(triadeFasceOrarie wed14 wed15 wed16)
(triadeFasceOrarie wed15 wed16 wed17)
(triadeFasceOrarie wed16 wed17 wed18)

(quartettoFasceOrarie wed08 wed09 wed10 wed11)
(quartettoFasceOrarie wed09 wed10 wed11 wed12)
(quartettoFasceOrarie wed10 wed11 wed12 wed13)
(quartettoFasceOrarie wed11 wed12 wed13 wed14)
(quartettoFasceOrarie wed12 wed13 wed14 wed15)
(quartettoFasceOrarie wed13 wed14 wed15 wed16)
(quartettoFasceOrarie wed14 wed15 wed16 wed17)
(quartettoFasceOrarie wed15 wed16 wed17 wed18)

(coppiaFasceOrarie thu08 thu09)
(coppiaFasceOrarie thu09 thu10)
(coppiaFasceOrarie thu10 thu11)
(coppiaFasceOrarie thu11 thu12)
(coppiaFasceOrarie thu12 thu13)
(coppiaFasceOrarie thu13 thu14)
(coppiaFasceOrarie thu14 thu15)
(coppiaFasceOrarie thu15 thu16)
(coppiaFasceOrarie thu16 thu17)
(coppiaFasceOrarie thu17 thu18)

(triadeFasceOrarie thu08 thu09 thu10)
(triadeFasceOrarie thu09 thu10 thu11)
(triadeFasceOrarie thu10 thu11 thu12)
(triadeFasceOrarie thu11 thu12 thu13)
(triadeFasceOrarie thu12 thu13 thu14)
(triadeFasceOrarie thu13 thu14 thu15)
(triadeFasceOrarie thu14 thu15 thu16)
(triadeFasceOrarie thu15 thu16 thu17)
(triadeFasceOrarie thu16 thu17 thu18)

(quartettoFasceOrarie thu08 thu09 thu10 thu11)
(quartettoFasceOrarie thu09 thu10 thu11 thu12)
(quartettoFasceOrarie thu10 thu11 thu12 thu13)
(quartettoFasceOrarie thu11 thu12 thu13 thu14)
(quartettoFasceOrarie thu12 thu13 thu14 thu15)
(quartettoFasceOrarie thu13 thu14 thu15 thu16)
(quartettoFasceOrarie thu14 thu15 thu16 thu17)
(quartettoFasceOrarie thu15 thu16 thu17 thu18)

(coppiaFasceOrarie fri08 fri09)
(coppiaFasceOrarie fri09 fri10)
(coppiaFasceOrarie fri10 fri11)
(coppiaFasceOrarie fri11 fri12)
(coppiaFasceOrarie fri12 fri13)
(coppiaFasceOrarie fri13 fri14)
(coppiaFasceOrarie fri14 fri15)
(coppiaFasceOrarie fri15 fri16)
(coppiaFasceOrarie fri16 fri17)
(coppiaFasceOrarie fri17 fri18)

(triadeFasceOrarie fri08 fri09 fri10)
(triadeFasceOrarie fri09 fri10 fri11)
(triadeFasceOrarie fri10 fri11 fri12)
(triadeFasceOrarie fri11 fri12 fri13)
(triadeFasceOrarie fri12 fri13 fri14)
(triadeFasceOrarie fri13 fri14 fri15)
(triadeFasceOrarie fri14 fri15 fri16)
(triadeFasceOrarie fri15 fri16 fri17)
(triadeFasceOrarie fri16 fri17 fri18)

(quartettoFasceOrarie fri08 fri09 fri10 fri11)
(quartettoFasceOrarie fri09 fri10 fri11 fri12)
(quartettoFasceOrarie fri10 fri11 fri12 fri13)
(quartettoFasceOrarie fri11 fri12 fri13 fri14)
(quartettoFasceOrarie fri12 fri13 fri14 fri15)
(quartettoFasceOrarie fri13 fri14 fri15 fri16)
(quartettoFasceOrarie fri14 fri15 fri16 fri17)
(quartettoFasceOrarie fri15 fri16 fri17 fri18)


(= (costoFasciaOraria mon08) 1)
(= (costoFasciaOraria mon09) 2)
(= (costoFasciaOraria mon10) 3)
(= (costoFasciaOraria mon11) 4)
(= (costoFasciaOraria mon12) 5)
(= (costoFasciaOraria mon13) 6)
(= (costoFasciaOraria mon14) 7)
(= (costoFasciaOraria mon15) 8)
(= (costoFasciaOraria mon16) 9)
(= (costoFasciaOraria mon17) 10)
(= (costoFasciaOraria mon18) 11)
(= (costoFasciaOraria tue08) 1)
(= (costoFasciaOraria tue09) 2)
(= (costoFasciaOraria tue10) 3)
(= (costoFasciaOraria tue11) 4)
(= (costoFasciaOraria tue12) 5)
(= (costoFasciaOraria tue13) 6)
(= (costoFasciaOraria tue14) 7)
(= (costoFasciaOraria tue15) 8)
(= (costoFasciaOraria tue16) 9)
(= (costoFasciaOraria tue17) 10)
(= (costoFasciaOraria tue18) 11)
(= (costoFasciaOraria wed08) 1)
(= (costoFasciaOraria wed09) 2)
(= (costoFasciaOraria wed10) 3)
(= (costoFasciaOraria wed11) 4)
(= (costoFasciaOraria wed12) 5)
(= (costoFasciaOraria wed13) 6)
(= (costoFasciaOraria wed14) 7)
(= (costoFasciaOraria wed15) 8)
(= (costoFasciaOraria wed16) 9)
(= (costoFasciaOraria wed17) 10)
(= (costoFasciaOraria wed18) 11)
(= (costoFasciaOraria thu08) 1)
(= (costoFasciaOraria thu09) 2)
(= (costoFasciaOraria thu10) 3)
(= (costoFasciaOraria thu11) 4)
(= (costoFasciaOraria thu12) 5)
(= (costoFasciaOraria thu13) 6)
(= (costoFasciaOraria thu14) 7)
(= (costoFasciaOraria thu15) 8)
(= (costoFasciaOraria thu16) 9)
(= (costoFasciaOraria thu17) 10)
(= (costoFasciaOraria thu18) 11)
(= (costoFasciaOraria fri08) 1)
(= (costoFasciaOraria fri09) 2)
(= (costoFasciaOraria fri10) 3)
(= (costoFasciaOraria fri11) 4)
(= (costoFasciaOraria fri12) 5)
(= (costoFasciaOraria fri13) 6)
(= (costoFasciaOraria fri14) 7)
(= (costoFasciaOraria fri15) 8)
(= (costoFasciaOraria fri16) 9)
(= (costoFasciaOraria fri17) 10)
(= (costoFasciaOraria fri18) 11)

(= (total-cost) 0)
)

(:goal (and
(fissato sistemiDigitali_1)
(fissato sistemiDigitali_2)
(fissato sistemiDigitali_3)
(fissato analisi_1)
(fissato analisi_2)
(fissato analisi_3)
(fissato componenti_1)
(fissato componenti_2)
(fissato componenti_3)
(fissato componenti_4)
(fissato componenti_5)
(fissato componenti_6)
(fissato componenti_7)
(fissato sistemiDiMisura_1)
(fissato sistemiDiMisura_2)
(fissato sistemiDiMisura_3)
(fissato sistemiDiMisura_4)
(fissato sistemiDiMisura_5)
(fissato sistemiDiMisura_6)
(fissato sistemiDiMisura_7)
(fissato sistemiDiMisura_8)
(fissato sistemiDiMisura_9)

))
(:metric minimize (total-cost))
)
    